export { ChangePasswordModal } from './ChangePasswordModal'
export { DeleteModal } from './DeleteModal'
export { InstanceFiltersModal } from './InstanceFiltersModal'
export { EditNameModal } from './EditNameModal'
export { ConfirmModal } from './ConfirmModal'
