apiVersion: v1
kind: Service
metadata:
  name: bill-service
  namespace: {{ NAMESPACE }}
spec:
  selector:
    app: bill
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http