apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-helper-secrets
  namespace: {{ NAMESPACE }}
stringData:
  AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
  AWS_ACCOUNT: "{{ AWS_ACCOUNT }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecr-registry-helper-cm
  namespace: {{ NAMESPACE }}
data:
  NAMESPACE_NAME: "{{ NAMESPACE }}"
  AWS_REGION: "{{ AWS_REGION }}"
  DOCKER_SECRET_NAME: 'regcred'