apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomro-bill-deployment
  labels:
    app: zomro-bill
  namespace: {NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zomro-bill
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: zomro-bill
    spec:
      containers:
        - name: zomro-bill
          image: zomrocom/zomro-bill
          resources:
            requests:
              memory: '10Mi'
              cpu: '10m'
            limits:
              memory: '100Mi'
              cpu: '100m'
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
            - name: https
              protocol: TCP
              containerPort: 8443
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: zomro-bill-service
  namespace: {NAMESPACE}
spec:
  selector:
    app: zomro-bill
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
