apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomro-bill-prod-deployment
  labels:
    app: zomro-bill-prod
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomro-bill-prod
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: zomro-bill-prod
    spec:
      containers:
        - name: zomro-bill-prod
          image: zomrocom/zomro-bill-prod
          resources:
            requests:
              memory: '64Mi'
              cpu: '200m'
            limits:
              memory: '128Mi'
              cpu: '250m'
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
            - name: https
              protocol: TCP
              containerPort: 8443
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: zomro-bill-prod-service
  namespace: prod
spec:
  selector:
    app: zomro-bill-prod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
