apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill-deployment
  labels:
    app: bill
  namespace: {{ NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bill
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app: bill
    spec:
      containers:
        - name: bill
          image: {{ IMAGE }}
          resources:
            requests:
              memory: '10Mi'
              cpu: '10m'
            limits:
              memory: '100Mi'
              cpu: '100m'
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
            - name: https
              protocol: TCP
              containerPort: 8443
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
