export { default as Logo } from './svg/Logo.jsx'

export { default as CsvDoc } from './svg/CsvDoc.jsx'
export { default as Calendar } from './svg/Calendar.jsx'

export { default as Eye } from './svg/Eye.jsx'
export { default as EyeClosed } from './svg/EyeClosed.jsx'

export { default as Pin } from './svg/Pin.jsx'
export { default as Box } from './svg/Box.jsx'
export { default as Wallet } from './svg/Wallet.jsx'
export { default as Social } from './svg/Social.jsx'
export { default as Support } from './svg/Support.jsx'

export { default as Facebook } from './svg/Facebook.jsx'
export { default as Google } from './svg/Google.jsx'
export { default as Vk } from './svg/Vk.jsx'

export { default as FacebookSmall } from './svg/FacebookSmall.jsx'
export { default as VkSmall } from './svg/VkSmall.jsx'

export { default as Moon } from './svg/Moon.jsx'
export { default as Sun } from './svg/Sun.jsx'

export { default as Cross } from './svg/Cross.jsx'

export { default as Shevron } from './svg/Shevron.jsx'
export { default as Search } from './svg/Search.jsx'
export { default as Envelope } from './svg/Envelope.jsx'
export { default as Padlock } from './svg/Padlock.jsx'

export { default as CalendarArrowDouble } from './svg/CalendarArrowDouble.jsx'
export { default as CalendarArrow } from './svg/CalendarArrow.jsx'
export { default as Person } from './svg/Person.jsx'
export { default as FilledEnvelope } from './svg/FilledEnvelope.jsx'
export { default as Bell } from './svg/Bell.jsx'
export { default as Profile } from './svg/Profile.jsx'
export { default as ExitSign } from './svg/ExitSign.jsx'
export { default as ArrowSign } from './svg/ArrowSign.jsx'

export { default as Settings } from './svg/Settings.jsx'
export { default as Key } from './svg/Key.jsx'
export { default as Delete } from './svg/Delete.jsx'
export { default as Copy } from './svg/Copy.jsx'
export { default as Filter } from './svg/Filter.jsx'
export { default as Chats } from './svg/Chats.jsx'
export { default as SendArchive } from './svg/SendArchive.jsx'
export { default as Download } from './svg/Download.jsx'
export { default as Like } from './svg/Like.jsx'
export { default as DisLike } from './svg/DisLike.jsx'
export { default as Clip } from './svg/Clip.jsx'
export { default as Check } from './svg/Check.jsx'
export { default as Info } from './svg/Info.jsx'
export { default as Pdf } from './svg/Pdf.jsx'
export { default as MoreDots } from './svg/MoreDots.jsx'
export { default as Error404_dt } from './svg/Error404_dt.jsx'
export { default as Error404_lt } from './svg/Error404_lt.jsx'

export { default as Pay } from './svg/Pay.jsx'
export { default as SuccessPay } from './svg/SuccessPay.jsx'
export { default as ErrorPay } from './svg/ErrorPay.jsx'

export { default as Edit } from './svg/Edit.jsx'
export { default as Clock } from './svg/Clock.jsx'
export { default as Refund } from './svg/Refund.jsx'
export { default as Transfer } from './svg/Transfer.jsx'
export { default as Whois } from './svg/Whois.jsx'
export { default as DomainsListName } from './svg/DomainsListName.jsx'
export { default as On_Off } from './svg/On_Off.jsx'
export { default as Print } from './svg/Print.jsx'
export { default as DownloadWithFolder } from './svg/DownloadWithFolder.jsx'
export { default as IP } from './svg/IP.jsx'
export { default as PassChange } from './svg/PassChange.jsx'
export { default as Reload } from './svg/Reload.jsx'
export { default as InProgress } from './svg/InProgress.jsx'
export { default as CheckCircle } from './svg/CheckCircle.jsx'
export { default as Attention } from './svg/Attention.jsx'
export { default as Flag } from './svg/Flag.jsx'
export { default as Exchange } from './svg/Exchange'
export { default as ChangeTariff } from './svg/ChangeTariff.jsx'

export { default as Infinity } from './svg/Infinity.jsx'
export { default as Euro } from './svg/Euro.jsx'
export { default as Smile } from './svg/Smile.jsx'

export { default as SiteCareIcon } from './svg/SiteCareIcon.jsx'
export { default as Plus } from './svg/Plus.jsx'
export { default as VpnIcon } from './svg/VpnIcon.jsx'

export { default as Germany } from './svg/Germany.jsx'
export { default as Usa } from './svg/Usa.jsx'
