export { default as Logo } from './svg/Logo'

export { default as CsvDoc } from './svg/CsvDoc'
export { default as Calendar } from './svg/Calendar'

export { default as Eye } from './svg/Eye'
export { default as EyeClosed } from './svg/EyeClosed'

export { default as Pin } from './svg/Pin'
export { default as Box } from './svg/Box'
export { default as Wallet } from './svg/Wallet'
export { default as Social } from './svg/Social'
export { default as Support } from './svg/Support'
export { default as WalletBalance } from './svg/WalletBalance'

export { default as HintHelp } from './svg/HintHelp'
export { default as Trash } from './svg/Trash'

export { default as PaymentProcessing } from './svg/PaymentProcessing'

export { default as EditPencil } from './svg/EditPencil'

export { default as Facebook } from './svg/Facebook'
export { default as Google } from './svg/Google'
export { default as Vk } from './svg/Vk'

export { default as FacebookSmall } from './svg/FacebookSmall'
export { default as VkSmall } from './svg/VkSmall'

export { default as Moon } from './svg/Moon'
export { default as Sun } from './svg/Sun'

export { default as Cross } from './svg/Cross'

export { default as Shevron } from './svg/Shevron'
export { default as Search } from './svg/Search'
export { default as Envelope } from './svg/Envelope'
export { default as Padlock } from './svg/Padlock'

export { default as CalendarArrowDouble } from './svg/CalendarArrowDouble'
export { default as CalendarArrow } from './svg/CalendarArrow'
export { default as Person } from './svg/Person'
export { default as FilledEnvelope } from './svg/FilledEnvelope'
export { default as Bell } from './svg/Bell'
export { default as Profile } from './svg/Profile'
export { default as ExitSign } from './svg/ExitSign'
export { default as ArrowSign } from './svg/ArrowSign'

export { default as Settings } from './svg/Settings'
export { default as Key } from './svg/Key'
export { default as Delete } from './svg/Delete'
export { default as Iso } from './svg/Iso'
export { default as DefaultOs } from './svg/DefaultOs'
export { default as Copy } from './svg/Copy'
export { default as Filter } from './svg/Filter'
export { default as Chats } from './svg/Chats'
export { default as SendArchive } from './svg/SendArchive'
export { default as Download } from './svg/Download'
export { default as Like } from './svg/Like'
export { default as DisLike } from './svg/DisLike'
export { default as Clip } from './svg/Clip'
export { default as Check } from './svg/Check'
export { default as CheckFat } from './svg/CheckFat'
export { default as Info } from './svg/Info'
export { default as Pdf } from './svg/Pdf'
export { default as MoreDots } from './svg/MoreDots'
export { default as Error404_dt } from './svg/Error404_dt'
export { default as Error404_lt } from './svg/Error404_lt'

export { default as Pay } from './svg/Pay'
export { default as SuccessPay } from './svg/SuccessPay'
export { default as ErrorPay } from './svg/ErrorPay'

export { default as Edit } from './svg/Edit'
export { default as Clock } from './svg/Clock'
export { default as Refund } from './svg/Refund'
export { default as Transfer } from './svg/Transfer'
export { default as Whois } from './svg/Whois'
export { default as DomainsListName } from './svg/DomainsListName'
export { default as On_Off } from './svg/On_Off'
export { default as Print } from './svg/Print'
export { default as DownloadWithFolder } from './svg/DownloadWithFolder'
export { default as IP } from './svg/IP'
export { default as PassChange } from './svg/PassChange'
export { default as Reload } from './svg/Reload'
export { default as InProgress } from './svg/InProgress'
export { default as CheckCircle } from './svg/CheckCircle'
export { default as CheckRound } from './svg/CheckRound'
export { default as Attention } from './svg/Attention'
export { default as Flag } from './svg/Flag'
export { default as Exchange } from './svg/Exchange'
export { default as ChangeTariff } from './svg/ChangeTariff'
export { default as Infinity } from './svg/Infinity'
export { default as Euro } from './svg/Euro'
export { default as Smile } from './svg/Smile'

export { default as SiteCareIcon } from './svg/SiteCareIcon'
export { default as Plus } from './svg/Plus'
export { default as VpnIcon } from './svg/VpnIcon'

export { default as Germany } from './svg/Germany'
export { default as Usa } from './svg/Usa'
export { default as Gift } from './svg/Gift'
export { default as GiftDt } from './svg/GiftDt'

export { default as CheckEdit } from './svg/CheckEdit'
export { default as SaleFiftyFive } from './svg/SaleFiftyFive'

export { default as Client } from './svg/Client'
export { default as Cloud } from './svg/Cloud'
export { default as Services } from './svg/Services'
export { default as Finance } from './svg/Finance'
export { default as Help } from './svg/Help'
export { default as Instruments } from './svg/Instruments'
export { default as Statistic } from './svg/Statistic'
export { default as Reference } from './svg/Reference'
export { default as Home } from './svg/Home'
export { default as Money } from './svg/Money'
export { default as Timer } from './svg/Timer'

export { default as PhoneVerificationIcon } from './svg/PhoneVerificationIcon'
export { default as Singapore } from './svg/Singapore'
export { default as ChangePassword } from './svg/ChangePassword'
export { default as Console } from './svg/Console'
export { default as Headphone } from './svg/Headphone'
export { default as Instruction } from './svg/Instruction'
export { default as Reboot } from './svg/Reboot'
export { default as Rebuild } from './svg/Rebuild'
export { default as Remove } from './svg/Remove'
export { default as Rename } from './svg/Rename'
export { default as Rescue } from './svg/Rescue'
export { default as Resize } from './svg/Resize'
export { default as Shelve } from './svg/Shelve'
export { default as Shutdown } from './svg/Shutdown'
export { default as AlmaLinux } from './svg/AlmaLinux'
export { default as CentOS } from './svg/CentOS'
export { default as Debian } from './svg/Debian'
export { default as Rocky } from './svg/Rocky'
export { default as Ubuntu } from './svg/Ubuntu'
export { default as Windows } from './svg/Windows'
export { default as Sort_a_z } from './svg/Sort_a_z'
export { default as Sort_z_a } from './svg/Sort_z_a'
export { default as Ssh_keys } from './svg/Ssh_keys'
export { default as Lock } from './svg/Lock'
export { default as Check_square } from './svg/Check_square'
export { default as Close_square } from './svg/Close_square'
export { default as Wrench } from './svg/Wrench'
export { default as Cube } from './svg/Cube'
export { default as Update } from './svg/Update'
export { default as Protected } from './svg/Protected'
export { default as Restore } from './svg/Restore'
export { default as Launch } from './svg/Launch'
export { default as DownloadImage } from './svg/DownloadImage'
export { default as Warning_triangle } from './svg/Warning_triangle'
