export { default as AuthPage } from './AuthPage/AuthPage'
export { default as MainPage } from './MainPage/MainPage'
export { default as AccessLogPage } from './AccessLogPage/AccessLogPage'
export { default as SupportPage } from './SupportPage/SupportPage'
export { default as OpenedTicker } from './SupportPage/OpenedTicket/OpenedTicket'
export { default as AboutAffiliateProgram } from './AffiliateProgram/AboutAffiliateProgram/AboutAffiliateProgram'
