apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-ci-cd-deploy
  namespace: {{ NAMESPACE }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-ci-cd-deploy
  namespace: {{ NAMESPACE }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - watch
      - get
      - patch
      - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding-ci-cd-deploy
  namespace: {{ NAMESPACE }}
subjects:
  - kind: ServiceAccount
    name: sa-ci-cd-deploy
    namespace: {{ NAMESPACE }}
roleRef:
  kind: Role
  name: role-ci-cd-deploy
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: ci-cd-deploy-secret
  namespace: {{ NAMESPACE }}
  annotations:
    kubernetes.io/service-account.name: sa-ci-cd-deploy