export { default as useOutsideAlerter } from './hooks/outsideClick'
export { default as usePageRender } from './hooks/usePageRender'
export { default as useScrollToElement } from './hooks/useScrollToElement'
export { default as useAnalyticsSender } from './hooks/useAnalyticsSender'

export { default as isBase64 } from './isBase64'
export { default as ipRegex } from './ipRegex'
export { default as checkIfTokenAlive } from './checkIfTokenAlive'
export { default as renameAddonFields } from './renameAddonFields'
export { DOMAIN_REGEX } from './constants'
export { default as translatePeriod } from './translatePeriod'
export { default as historyTranslateFn } from './historyTranslateFn'
export { default as expensesTranslateFn } from './expensesTranslateFn'
export { default as checkServicesRights } from './checkServicesRights'
export { default as notificationsTranslateFn } from './notificationsTranslateFn'
export { default as replaceAllFn } from './replaceAllFn'
export { default as systemNotificationsTranslate } from './systemNotificationsTranslate'
export { default as translateSupportPaymentError } from './translateSupportPaymentError'
export { default as shortTitle } from './shortTitle'
export { default as cookies } from './cookies'
export { default as parseLang } from './parseLangToSite'
export { default as orderDetailTranslate } from './orderDetailTranslate'
export { default as translatePeriodToMonths } from './translatePeriodToMonths'
export { default as fraudCheckSender } from './fraudCheckSender'
export { default as analyticsSaver } from './analyticsSaver'
