apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-ci-cd-admin
  namespace: {{ NAMESPACE }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-ci-cd-admin
  namespace: {{ NAMESPACE }}
rules:
  - apiGroups: [ "" ]
    resources:
      - services
    verbs:
      - create
      - get
  - apiGroups: [ "" ]
    resources:
      - secrets
    verbs:
      - create
      - get
  - apiGroups: [ "" ]
    resources:
      - serviceaccounts
    verbs:
      - create
      - get
  - apiGroups: [rbac.authorization.k8s.io]
    resources:
      - roles
      - rolebindings
    verbs:
      - get
      - create
  - apiGroups: [ networking.k8s.io ]
    resources:
      - ingresses
    verbs:
      - create
      - get
      - patch

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding-ci-cd-admin
  namespace: {{ NAMESPACE }}
subjects:
  - kind: ServiceAccount
    name: sa-ci-cd-admin
    namespace: {{ NAMESPACE }}
roleRef:
  kind: Role
  name: role-ci-cd-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: ci-cd-admin-secret
  namespace: {{ NAMESPACE }}
  annotations:
    kubernetes.io/service-account.name: sa-ci-cd-admin