export const CHANGE_PASSWORD = '/change_pass'
export const RESET_PASSWORD = '/reset_pass'
export const LOGIN = '/login'
export const REGISTRATION = '/signup'
export const HOME = '/'
export const ACCESS_LOG = '/access_log'
export const TRUSTED_USERS = '/trusted_users'
export const SUPPORT = '/support'
export const USER_SETTINGS = '/usrparam'
export const AFFILIATE_PROGRAM = '/affiliate'
export const AFFILIATE_PROGRAM_ABOUT = 'about'
export const AFFILIATE_PROGRAM_INCOME = 'income'
export const AFFILIATE_PROGRAM_STATISTICS = 'statistics'
export const BILLING = '/billing'

export const CONFIRM_EMAIL = '/confrim_email'

export const ERROR_PAGE = '/error_page'
export const SERVICES = '/services'
