name: Send Notification
on:
  workflow_run:
    workflows: ["*"]
    types:
      - completed


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  on-failure:
    name: Send message
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: |
            Please check <${{ github.event.workflow_run.html_url }}|action>
            ${{ vars.STACK_DEVOPS_TRIGGER }}
          SLACK_TITLE: Fail complete workflow
          SLACK_USERNAME: Check workflow
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}