name: Update branch

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  create_pull_request:
    name: Update branch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - head: dev # з якої гілки
            base: update # до якої гілки
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.head }}

      - name: Delete branch
        run: | 
          git push -d ${{ github.server_url }}/${{ github.repository }} ${{ matrix.base }} || true

      - name: Create branch
        run: |
          git push ${{ github.server_url }}/${{ github.repository }} ${{ matrix.head }}:${{ matrix.base }} 

  run_workflow:
    needs: [ create_pull_request ]
    name: Run workflow - deployment
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    uses: ./.github/workflows/deploy.yaml
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-run_manual
      cancel-in-progress: true
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
