name: Update branch

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  createPullRequest:
    name: Update branch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - head: dev # з якої гілки
            base: bill-update # до якої гілки
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.head }}

      - name: Configurate github
        run: |
          git config --global user.email "oleksiy.moturnyak@zomro.org"
          git config --global user.name "user-a54"

      - name: Delete branch
        run: | 
          git push -d ${{ github.server_url }}/${{ github.repository }} ${{ matrix.base }} || true

      - name: Create branch
        run: |
          git checkout -b ${{ matrix.base }}
          git commit --allow-empty -m "Trigger"
          git push ${{ github.server_url }}/${{ github.repository }} ${{ matrix.base }}:${{ matrix.base }} 
          git commit --allow-empty -m "Trigger"
          git push ${{ github.server_url }}/${{ github.repository }} ${{ matrix.base }}:${{ matrix.base }} 
